replicaCount: 3

image:
  repository: your_container_registry_name/example-microservice
  tag: your_tag
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 200m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

mongoSecret:
  name: your-mongo-secret

nodeEnv: production
